# Generated by Django 2.0.5 on 2020-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200707_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='post',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Average rating'),
        ),
    ]
